baseURL = 'https://m346.frickelbude.ch'
languageCode = 'de-ch'
title = 'Modul 346'
enableEmoji = true

[minify]
minifyOutput = true

[params]
disableInlineCopyToClipBoard = true
math = true
openapi = false
showVisitedLinks = true
collapsibleMenu = true
themeVariant = 'green'
hideAuthorDate = true

[params.author]
name = 'Patrick Bucher'

[module]
[[module.imports]]
path = 'github.com/McShelby/hugo-theme-relearn'
